### ISSUE TITLE
Feature request - Change current workspace

### ISSUE THREAD

**Issue by juan-kabbali** [idoavrah/terraform-tui#63]
Hello there!  I would like to propose a feature.

When TFTUI is open, it's done on the current workspaces which is logical. Then if you need to change the workspace, you should `quit` run `tf workspace select foo` and reopen TFTUI.

It should be nice to have some TFTUI command to do it inside the CLI interface. Something like `^W + workspace name`

If you consider if this request is relevant. I can propose a Pull Request.  

Please don't hesitate to ask more information or detail about this request.

**Comment by idoavrah** [comment]
Hi Juan,

I'm not using workspaces myself, that's why it's not included in the original TFTUI.
You're welcome to create a PR, I'll gladly add it to the product if it works. You'll probably need to add it in the GUI which may be a daunting task (specifically getting familiar with my spaghetti code :)).

I'll be happy to learn this specific TF feature and add it to the product myself, but I can't promise when I'll find the time to do that.

Let me know what you've decided.

**Comment by idoavrah** [comment]
Hey @juan-kabbali ,

Just released version 0.13.0, allowing switching workspaces from within the application.

Check it out, let me know what you think and if something's missing.

**Comment by juan-kabbali** [comment]
@idoavrah excellent, I tested version `0.13.0` and it works nice and smoothly 🚀

Thanks very much !
