### ISSUE TITLE
Add support for TF_VAR_<VALUE>

### ISSUE THREAD

**Issue by jz-wilson** [idoavrah/terraform-tui#73]
Hi, looking adding support for using `TF_VAR_<VALUE>` for variables used as from sourced environment variables. It seems like the sourced variables are not making into `tftui`.

I am currently using a Makefile to do this:

```shell
$(TASKS):
	. ${HOME}/.terraform/defaults/_$(ENV) && terraform $@ -var-file=env/$(ENV)/$(WS_REGION)/terraform.tfvars $(foreach var,$(TARGETS),-target=$(var)) $(ARGS)
```
I would just create a .tfvar file, but I don't need all the variables everytime.

Awesome work on this application btw!

**Comment by idoavrah** [comment]
Hi Johnzell,

I actually never used this feature in terraform and wasn't aware of it.
That being said, I did some tests and it seems that env vars do transfer to the `tftui` process (and through it to the `terraform plan` command that is executed within the application itself). 
Are you sure you're *exporting* those environment variables and not just setting them so that they'll be inherited by child processes?

Can you elaborate on the specific process you're going through so I can and duplicate it on my end?

**Comment by jz-wilson** [comment]
Nope, I wasn't exporting them... 

I have a bash script that would set the env vars, but I didn't set the export on them. 

Thanks.

I'm running this:

`. ~/.terraform/defaults/.dev && tftui -f env/dev/us-east-2/terraform.tfvars`

This worked for me.
